version: '2'
services:
  mysql:
    image: 137462835382.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
    environment:
      MYSQL_PASS: changeme
      STARTUP_SQL: /tmp/wordpress.sql

  vaurien:
    image: 137462835382.dkr.ecr.us-east-1.amazonaws.com/vaurien:latest
    environment:
      HOST: mysql
      BACKENDPORT: 3306
      PROXYPORT: 3306
      PROTO: mysql
    expose:
      - "3306"
      - "8081"
    restart: on-failure

  web:
    image: 137462835382.dkr.ecr.us-east-1.amazonaws.com/vaurien:latest
    expose:
      - "8081"
      - "80"
    environment:
      HOST: wordpress
      BACKENDPORT: 80
      PROXYPORT: 80
      PROTO: http
    restart: on-failure

  wordpress:
    image: 137462835382.dkr.ecr.us-east-1.amazonaws.com/wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: changeme
      WORDPRESS_DB_HOST: vaurien
    restart: on-failure

  jmeter:
    image: 137462835382.dkr.ecr.us-east-1.amazonaws.com/jmeter:latest
    environment:
      WORDPRESS_HOST: wordpress
      WORDPRESS_PORT: 80
      JMETER_OUTAGE: 0
    restart: on-failure
